# Generated by Django 3.2.5 on 2021-07-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210712_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(default=555, verbose_name='age'),
            preserve_default=False,
        ),
    ]
